import random
from typing import Dict, List

SPAWN_TEXTS: Dict[str, List[str]] = {
    "grassland": [
        "Você estava caminhando tranquilamente pela rota quando {name} pulou do mato!",
        "A grama alta começou a se mexer... era {name} selvagem!",
        "Enquanto observava as flores, {name} apareceu curioso.",
        "O vento balançou o campo e revelou um {name}!",
        "Do nada, um {name} correu pelo gramado e te encarou!",
        "Um barulho estranho surgiu do mato... era {name}!",
        "O som dos grilos foi interrompido por {name} surgindo!",
        "Enquanto descansava na relva, {name} te surpreendeu.",
        "Você chutou sem querer um arbusto e {name} saiu de lá!",
        "O sol brilhou forte, revelando um {name} selvagem!",
        "O cheiro de flores trouxe {name} até você.",
        "As borboletas voaram, assustadas por {name} chegando!",
        "Um {name} saltou do campo aberto bem na sua frente.",
        "De repente, o capim alto começou a se abrir... era {name}!",
        "Um vulto correu pela grama e parou: era {name}!",
        "Você estava quase cochilando, mas {name} apareceu.",
        "O vento trouxe um barulho esquisito... era {name} no gramado!",
        "Enquanto seguia pela rota, {name} pulou do nada!",
        "Um {name} curioso saiu da relva para te observar.",
        "O campo ficou silencioso até {name} surgir do nada.",
        "Um salto no meio da grama revelou {name} selvagem!",
        "Você ouviu passos leves... era {name} se aproximando!",
        "As flores balançaram... {name} estava escondido ali.",
        "De repente, uma sombra surgiu na relva: era {name}!",
        "Enquanto olhava o horizonte, {name} apareceu ao lado.",
    ],
    "forest": [
        "Entre as árvores sombrias, {name} surgiu de repente!",
        "Você ouviu passos na floresta... era {name}.",
        "Enquanto explorava o bosque, {name} saltou da sombra!",
        "O silêncio foi quebrado pelo rugido de {name}!",
        "Um {name} estava escondido atrás de uma árvore!",
        "A floresta ficou em silêncio... até {name} aparecer.",
        "O farfalhar das folhas revelou um {name} selvagem.",
        "De repente, {name} caiu de um galho bem na sua frente.",
        "Um grito assustador ecoou... era {name}!",
        "As sombras dançaram e mostraram {name} espreitando.",
        "Você tropeçou numa raiz e encontrou {name} parado.",
        "Os pássaros voaram assustados: {name} estava chegando.",
        "Enquanto seguia por uma trilha, {name} saltou do mato.",
        "Uma árvore balançou sozinha... {name} saiu dela!",
        "Um rugido ecoou entre as copas: era {name}!",
        "Você olhou para trás e {name} estava te seguindo.",
        "O som dos galhos quebrando revelou {name}.",
        "Uma sombra se moveu rápido... {name} apareceu!",
        "Enquanto descansava sob uma árvore, {name} caiu do alto.",
        "Você ouviu um sussurro e percebeu {name} na escuridão.",
        "Do nada, {name} saiu correndo entre as árvores.",
        "O sol mal passava pelas folhas, mas iluminou {name}!",
        "Os insetos pararam de zumbir... {name} estava lá.",
        "Uma árvore antiga se abriu revelando {name}.",
        "No silêncio da mata, {name} surgiu assustando você.",
    ],
    "cave": [
        "Você acendeu sua lanterna e viu {name} te observando nas pedras!",
        "Das profundezas da caverna, {name} surgiu!",
        "O eco revelou um rugido... era {name}.",
        "Uma sombra se moveu na escuridão: {name} selvagem!",
        "Você quase tropeçou em {name} dentro da caverna!",
        "As pedras começaram a cair... era {name} saindo da parede!",
        "Um som de asas ecoou... era {name} voando!",
        "As gotas da caverna caíram sobre {name} escondido.",
        "Sua lanterna piscou e revelou {name} na escuridão.",
        "O eco repetia o nome de {name}!",
        "Enquanto explorava, {name} caiu do teto.",
        "As paredes tremiam com a chegada de {name}.",
        "Um brilho nos cristais revelou {name}.",
        "De repente, {name} pulou de trás das estalactites.",
        "As estalagmites se moveram: era {name} disfarçado.",
        "Você ouviu respirações pesadas... era {name}.",
        "Uma sombra enorme tomou forma... {name}!",
        "O vento soprou dentro da caverna e trouxe {name}.",
        "Uma corrente subterrânea revelou {name} escondido.",
        "Enquanto se perdia nos túneis, {name} apareceu.",
        "Um grito profundo ecoou: era {name}!",
        "A escuridão total foi quebrada por {name}.",
        "Você ouviu pedras rolando... era {name}.",
        "De repente, {name} surgiu no meio do caminho estreito.",
        "O silêncio foi quebrado pelo rugido de {name}.",
    ],
    "mountain": [
        "No alto da montanha, {name} apareceu contra o vento!",
        "Entre os rochedos, {name} surgiu selvagem!",
        "Enquanto escalava, você deu de cara com {name}!",
        "O som das pedras rolando anunciou a chegada de {name}!",
        "O ar rarefeito não impediu {name} de aparecer!",
        "Uma sombra cruzou o céu... era {name} voando!",
        "O barulho de avalanche revelou {name}.",
        "De repente, {name} surgiu entre os penhascos.",
        "Um rugido ecoou pelas montanhas... era {name}!",
        "Enquanto descansava na trilha, {name} apareceu.",
        "As águias fugiram... {name} estava ali.",
        "Do topo de uma rocha, {name} pulou em sua frente.",
        "O som do vento trouxe {name} até você.",
        "Enquanto subia, {name} caiu de uma pedra.",
        "Um vulto se aproximou na neblina: era {name}!",
        "As pedras começaram a rolar... {name} surgiu!",
        "Você ouviu ecos nas montanhas: {name} estava perto.",
        "De repente, {name} se revelou entre as nuvens.",
        "Um {name} olhava de cima da colina, te encarando.",
        "Enquanto caminhava na trilha, {name} bloqueou o caminho.",
        "A paisagem montanhosa escondeu {name} até agora.",
        "Você quase caiu, mas {name} estava lá.",
        "Um clarão no topo revelou {name} selvagem.",
        "As pedras racharam e de lá saiu {name}.",
        "O vento forte trouxe {name} com ele.",
    ],
    "sea": [
        "As ondas se abriram e {name} emergiu com um enorme splash!",
        "Você estava no convés quando {name} saltou do oceano!",
        "Um brilho prateado no horizonte revelou {name}.",
        "O mar ficou revolto e {name} subiu até a superfície!",
        "Enquanto pescava, {name} puxou sua linha e apareceu!",
        "Um cardume se dispersou e, no centro, {name} surgiu.",
        "Uma onda encontrou a costa e trouxe {name} à praia!",
        "O sonar do barco detectou algo... era {name} nadando por baixo.",
        "Você viu uma sombra gigante debaixo d'água: {name}!",
        "O casco bateu em algo flutuante — era {name} agarrado!",
        "Uma nuvem de espuma revelou {name} dançando nas ondas.",
        "Do profundo azul, {name} emergiu e te encarou.",
        "Você ouviu um canto distante e então {name} apareceu.",
        "O farol piscou e mostrou {name} brincando na maré.",
        "Um jato d'água levantou-se e {name} apareceu no topo.",
        "Enquanto nadava, {name} passou raspando por você.",
        "As gaivotas alvoroçaram quando {name} rompeu a superfície.",
        "Uma trilha de bolhas levou você até {name}.",
        "O navio bateu em algo... era {name} escondido na água.",
        "A maré trouxe um objeto brilhante — e {name} estava em cima dele.",
        "Um redemoinho girou e {name} foi cuspido para fora.",
        "Do casco enferrujado no fundo, {name} saiu com brilho.",
        "Você viu um reflexo que não era seu: era {name} na água.",
        "Enquanto observava o horizonte, {name} surgiu e olhou para você.",
        "O barco sacudiu e, entre as ondas, estava {name}.",
    ],
    "urban": [
        "No meio da cidade, {name} surgiu do nada entre os pedestres!",
        "Você viu {name} espiando de dentro de uma lixeira.",
        "Um {name} atravessou a rua como se fosse dono do asfalto!",
        "Enquanto tomava café, {name} cruzou a calçada apressado.",
        "O transporte parou quando {name} apareceu na plataforma.",
        "Um reflexo na vitrine mostrou {name} atrás de você.",
        "No beco escuro, {name} olhava para as luzes da rua.",
        "Um som de sirene se misturou ao grito de {name}.",
        "Enquanto subia a escada rolante, {name} pulou ao seu lado.",
        "Um entregador deixou cair algo e {name} apareceu para pegar.",
        "As luzes neon tremularam quando {name} atravessou a avenida.",
        "Você abriu a porta do prédio e {name} entrou sem pedir licença.",
        "No telhado mais alto, {name} observava a cidade inteira.",
        "Um cachorro latiu e, no meio do tumulto, {name} surgiu.",
        "O metrô freou e {name} despontou na plataforma escura.",
        "As vitrines se apagaram e {name} apareceu iluminado por telas.",
        "Um bug na câmera de segurança mostrou {name} passando rápido.",
        "Enquanto cruzava o parque urbano, {name} surgiu entre os bancos.",
        "Um carrinho tombou e {name} aproveitou a confusão para aparecer.",
        "O semáforo piscou e, no cruzamento, {name} olhou para você.",
        "Você ia entrar na loja quando {name} saiu correndo por entre as prateleiras.",
        "No canto do quiosque, {name} estava roubando migalhas.",
        "O buzinaço parou quando {name} atravessou a rua correndo.",
        "Enquanto caminhava pela calçada, {name} esbarrou em você.",
        "O prédio foi tomado por um barulho estranho... era {name} no hall.",
    ],
    "rare": [
        "Um clarão cortou o céu e {name} materializou-se diante de você!",
        "As estrelas alinharam-se por um instante... e {name} apareceu.",
        "Você sentiu o tempo desacelerar: {name} estava ali.",
        "Um portal brilhou e, dele, saiu {name} como saída de lenda.",
        "O ar ficou elétrico e {name} surgiu com uma aura intensa.",
        "Um sussurro antigo chamou sua atenção... era {name}.",
        "O mundo pareceu piscar, e quando voltou, {name} estava no seu caminho.",
        "Uma música distante trouxe {name} das sombras da realidade.",
        "O solo abriu-se levemente e revelou {name} brilhando.",
        "Você teve a impressão de estar sonhando — até ver {name}.",
        "Um fenômeno raro no céu revelou {name} descendo em luz.",
        "Todas as bússolas falharam e apontaram para {name}.",
        "Um velho conto ganhou vida: ali estava {name}.",
        "A névoa ganhou tons dourados e {name} surgiu no centro.",
        "O silêncio do mundo inteiro foi quebrado por {name}.",
        "Uma arca antiga abriu-se e {name} saiu dela, único e imponente.",
        "O clima mudou num instante: {name} apareceu como profecia.",
        "Você sentiu arrepios e viu {name} emergir do nada.",
        "As sombras dançaram e formaram a silhueta de {name}.",
        "Um feixe de luz apontou para você... e lá estava {name}.",
        "O vento trouxe sussurros de outra era: {name} atendeu ao chamado.",
        "Um trovão sem nuvens rasgou o ar e {name} apareceu.",
        "As pessoas pararam e olharam para cima — {name} cruzou o céu.",
        "Uma força antiga se manifestou: {name} estava ali, real.",
        "Você pensou que era história... até {name} surgir bem na sua frente.",
    ],
    "rough-terrain": [
        "Entre as pedras afiadas, {name} apareceu saltando entre as fendas!",
        "O solo tremeu e {name} emergiu de uma rachadura na terra.",
        "Você quase escorregou numa pedra, e um {name} apareceu para lhe ver!",
        "O vento levantou pedras e revelou {name} escondido.",
        "Uma avalanche parcial deixou claro que {name} estava por perto.",
        "Enquanto desviava de rochas, {name} cruzou seu caminho.",
        "O terreno irregular fez você perder o passo — {name} sorriu.",
        "Um rugido ecoou entre as rochas: era {name} chegando.",
        "Do meio do cascalho, {name} saltou para te encarar.",
        "As pedras se abriram como se tivessem vida... e {name} saiu.",
        "Uma trilha pedregosa revelou pegadas de {name} até você.",
        "Você ouviu um estrondo baixo: {name} tinha acabado de mover uma pedra gigante.",
        "Enquanto escalava uma fenda, {name} te bloqueou a passagem.",
        "O solo se partiu e {name} apareceu em meio à poeira.",
        "Um brilho metálico entre as pedras revelou {name}.",
        "Você sentiu o chão ceder — e {name} surgiu com força.",
        "A trilha terminou em um penhasco e {name} estava no topo, observando.",
        "Pedras rolavam sozinhas, guiando você até {name}.",
        "Um barulho surdo trouxe {name} correndo pelo vale rochoso.",
        "Enquanto procurava abrigo, {name} saltou de uma cavidade na rocha.",
        "O vento cortante trouxe o cheiro de ferro... {name} estava ali.",
        "Uma rocha se moveu e revelou {name} camuflado.",
        "De uma fenda estreita, {name} esticou a cabeça e olhou para você.",
        "O chão formou pequenas crateras — {name} havia passado por ali.",
        "Você viu uma silhueta recortada contra o sol: {name} no topo do rochedo.",
    ],
    "waters-edge": [
        "Na beira da água, {name} estava bebendo calmamente quando te viu!",
        "Enquanto caminhava pela margem, {name} pulou na sua frente!",
        "O reflexo na água revelou {name} escondido entre as pedras.",
        "Você jogou uma pedra e, no splash, {name} apareceu bravo!",
        "Um salto das margens trouxe {name} correndo para você.",
        "Um aroma de algas denunciou a presença de {name} na beira.",
        "A lama se moveu e {name} surgiu devagar, coberto de terra.",
        "Você ouviu bolhas e então viu {name} sair da água rasa.",
        "Um som de peixe pulando precedeu a aparição de {name}.",
        "Enquanto pescava, {name} mordeu sua isca e apareceu.",
        "As pedras molhadas esconderam {name} até você chegar perto.",
        "Um reflexo estranho na água lhe mostrou {name} vindo.",
        "Você sentou na margem e {name} decidiu se aproximar curioso.",
        "Um movimento entre os juncos denunciou {name} espreitando.",
        "O som de asas batendo na superfície revelou {name}.",
        "A maré trouxe um objeto brilhante... e {name} estava em cima dele.",
        "Você escorregou na lama e, quando se levantou, {name} estava ao lado.",
        "As ondas pequenas espalharam uma trilha que levou a {name}.",
        "Enquanto passava pela ponte, {name} apareceu embaixo dela.",
        "O cheiro da água doce trouxe {name} até a margem.",
        "Uma pedra boiando revelou {name} agarrado nela.",
        "Você percebeu pegadas molhadas que terminavam em {name}.",
        "Um sapinho coaxou e, entre os coaxos, {name} surgiu.",
        "As rãs pularam e {name} emergiu para brincar.",
        "De repente, {name} deslizou para a margem e te encarou.",
    ],
}

def get_spawn_text(habitat: str, name: str) -> str:
    texts = SPAWN_TEXTS.get(habitat, SPAWN_TEXTS["grassland"])
    return random.choice(texts).format(name=name)